apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: meldekort-mikrofrontend
  namespace: meldekort
  labels:
    team: meldekort
spec:
  tokenx:
    enabled: true
  image: {{ image }}
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side
          namespace: min-side
    outbound:
      rules:
        - application: meldekort-api-q2
        - application: dp-meldekortregister
          namespace: teamdagpenger
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
  env:
    - name: MELDEKORT_API_AUDIENCE
      value: "dev-gcp:meldekort:meldekort-api-q2"
    - name: MELDEKORT_API_URL
      value: "http://meldekort-api-q2.meldekort/meldekort/meldekort-api/api/person/meldekortstatus"
    - name: MELDEKORTREGISTER_AUDIENCE
      value: "dev-gcp:teamdagpenger:dp-meldekortregister"
    - name: MELDEKORTREGISTER_URL
      value: "http://dp-meldekortregister.teamdagpenger/meldekortstatus"
    - name: MELDEKORT_URL
      value: "https://meldekort-frontend-q2.intern.dev.nav.no/meldekort"
    - name: ETTERREGISTRERING_MELDEKORT_URL
      value: "https://www.dev.nav.no/meldekort/etterregistrer-meldekort"
